# Scrubbing and Cleaning Data - Lab

## Introduction

In the previous labs, you joined the data from our separate files into a single DataFrame.  In this lab, you'll scrub the data to get it ready for exploration and modeling!

## Objectives

You will be able to:

* Cast columns to the appropriate data types
* Identify and deal with null values appropriately
* Remove unnecessary columns
* Understand how to normalize data


## Getting Started

You'll find the resulting dataset from your work in the _Obtaining Data_ Lab stored within the file `'Lego_data_merged.csv'`.  

In the cells below:

* Import `pandas` and set the standard alias. 
* Import `numpy` and set the standard alias. 
* Import `matplotlib.pyplot` and set the standard alias. 
* Import `seaborn` and set the alias `sns` (this is the standard alias for seaborn). 
* Use the ipython magic command to set all matplotlib visualizations to display inline in the notebook. 
* Load the dataset stored in the `'Lego_data_merged.csv'` file into a DataFrame, `df`. 
* Inspect the head of the DataFrame to ensure everything loaded correctly. 

In [2]:
# Import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [3]:
# Now, load in the dataset and inspect the head to make sure everything loaded correctly
df = pd.read_csv('Lego_data_merged.csv')
df.head()

prod_id  ages  piece_count                        set_name  \
0    75823  6-12          277           Bird Island Egg Heist   
1    75822  6-12          168              Piggy Plane Attack   
2    75821  6-12           74                Piggy Car Escape   
3    21030   12+         1032  United States Capitol Building   
4    21035   12+          744   Solomon R. Guggenheim Museum®   

                                           prod_desc  \
0  Catapult into action and take back the eggs fr...   
1  Launch a flying attack and rescue the eggs fro...   
2  Chase the piggy with lightning-fast Chuck and ...   
3  Explore the architecture of the United States ...   
4  Recreate the Solomon R. Guggenheim Museum® wit...   

                                      prod_long_desc    theme_name country  \
0  Use the staircase catapult to launch Red into ...  Angry Birds™      US   
1  Pilot Pig has taken off from Bird Island with ...  Angry Birds™      US   
2  Pitch speedy bird Chuck against the Piggy Car....  Angry Birds™      US   
3  Discover the architectural secrets of the icon...  Architecture      US   
4  Discover the architectural secrets of Frank Ll...  Architecture      US   

  list_price  num_reviews  play_star_rating review_difficulty  star_rating  \
0     $29.99          2.0               4.0           Average          4.5   
1     $19.99          2.0               4.0              Easy          5.0   
2     $12.99         11.0               4.3              Easy          4.3   
3     $99.99         23.0               3.6           Average          4.6   
4     $79.99         14.0               3.2       Challenging          4.6   

   val_star_rating  
0              4.0  
1              4.0  
2              4.1  
3              4.3  
4              4.1

## Starting our Data Cleaning

To start, you'll deal with the most obvious issue: data features with the wrong data encoding.

### Checking Data Types

In the cell below, use the appropriate method to check the data type of each column. 

In [4]:
# Your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 14 columns):
prod_id              10870 non-null int64
ages                 10870 non-null object
piece_count          10870 non-null int64
set_name             10870 non-null object
prod_desc            10512 non-null object
prod_long_desc       10870 non-null object
theme_name           10870 non-null object
country              10870 non-null object
list_price           10870 non-null object
num_reviews          9449 non-null float64
play_star_rating     9321 non-null float64
review_difficulty    9104 non-null object
star_rating          9449 non-null float64
val_star_rating      9301 non-null float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.2+ MB


Now, investigate some of the unique values inside of the `list_price` column.

In [10]:
# Your code here
df.list_price.unique()

array(['$29.99', '$19.99', '$12.99', '$99.99', '$79.99', '$59.99',
       '$49.99', '$39.99', '$34.99', '$159.99', '$9.99', '$199.99',
       '$149.99', '$119.99', '$89.99', '$69.99', '$24.99', '$15.99',
       '$14.99', '$6.99', '$16.99', '$7.99', '$4.99', '$2.49', '$369.99',
       '$169.99', '$279.99', '$249.99', '$239.99', '$139.99', '$269.99',
       '$129.99', '$44.99', '$11.99', '$349.99', '$5.99', '$109.99',
       '$54.99', '$32.99', '$197.99', '$88.99', '$41.99', '$31.99',
       '$26.99', '$21.99', '$3.99', '$299.99', '$754.99', '$484.99',
       '$36.99', '$789.99', '$499.99', '$84.99', '$799.99', '$289.99',
       '$179.99', '$113.9924', '$75.9924', '$60.7924', '$53.1924',
       '$45.59240000000001', '$37.9924', '$189.9924', '$30.3924',
       '$22.7924', '$12.1524', '$227.9924', '$174.7924', '$121.5924',
       '$34.1924', '$18.9924', '$17.4724', '$13.6724', '$7.5924',
       '$15.1924', '$9.8724', '$6.0724', '$2.2724', '$91.1924',
       '$379.9924', '$303.9924000000001

### Numerical Data Stored as Strings

A common issue to check for at this stage is numeric columns that have accidentally been encoded as strings. For example, you should notice that the `list_price` column above is currently formatted as a string and contains a proceeding '$'. Remove this and convert the remaining number to a `float` so that you can later model this value. After all, your primary task is to generate model to predict the price.

> Note: While the data spans a multitude of countries, assume for now that all prices have been standardized to USD.

In [13]:
# Your code here
df.list_price = [x.strip('$') for x in df.list_price]
df.list_price = df.list_price.astype(float)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 14 columns):
prod_id              10870 non-null int64
ages                 10870 non-null object
piece_count          10870 non-null int64
set_name             10870 non-null object
prod_desc            10512 non-null object
prod_long_desc       10870 non-null object
theme_name           10870 non-null object
country              10870 non-null object
list_price           10870 non-null float64
num_reviews          9449 non-null float64
play_star_rating     9321 non-null float64
review_difficulty    9104 non-null object
star_rating          9449 non-null float64
val_star_rating      9301 non-null float64
dtypes: float64(5), int64(2), object(7)
memory usage: 1.2+ MB


### Detecting and Dealing With Null Values

Next, it's time to check for null values. How to deal with the null values will be determined by the columns containing them, and how many null values exist in each.  
 
In the cell below, get a count of how many null values exist in each column in the DataFrame. 

In [16]:
# Your code here
df.isna().sum()

prod_id                 0
ages                    0
piece_count             0
set_name                0
prod_desc             358
prod_long_desc          0
theme_name              0
country                 0
list_price              0
num_reviews          1421
play_star_rating     1549
review_difficulty    1766
star_rating          1421
val_star_rating      1569
dtype: int64

Now, get some descriptive statistics for each of the columns. You want to see where the minimum and maximum values lie.  

In [44]:
# Your code here
df.prod_desc.unique()

array(['Catapult into action and take back the eggs from the Piggy Trike!',
       'Launch a flying attack and rescue the eggs from the Piggy Plane!',
       'Chase the piggy with lightning-fast Chuck and rescue the eggs!',
       'Explore the architecture of the United States Capitol Building!',
       'Recreate the Solomon R. Guggenheim Museum® with LEGO® Architecture!',
       'Celebrate Shanghai with this LEGO® Architecture Skyline set!',
       'Celebrate New York City with this LEGO® Architecture Skyline model!',
       'Recreate Buckingham Palace with LEGO® Architecture!',
       'Celebrate London with this LEGO® Architecture Skyline model!',
       'Celebrate Chicago with this LEGO® Architecture Skyline model!',
       'Experience the grandeur of the Arc de Triomphe!',
       'Build your own LEGO® interpretation of the iconic Eiffel Tower!',
       'Celebrate Sydney with this LEGO® Architecture Skyline model!',
       'Bring your LEGO® creations to life!',
       'Build a LEGO®

In [45]:
print(df.num_reviews.max())
print(df.num_reviews.min())
df.num_reviews.unique()

367.0
1.0


array([  2.,  11.,  23.,  14.,   7.,  37.,  24.,  53.,  63.,  13.,   1.,
         3.,   5.,  nan,   4.,   6.,   8.,   9.,  10.,  12.,  35.,  45.,
        16.,  89.,  47.,  85.,  40.,  30.,  46., 180.,  27.,  15.,  43.,
        62.,  51.,  99.,  64., 228.,  91., 115., 202., 177., 337.,  66.,
       134.,  77.,  19.,  18.,  32., 171.,  52.,  22.,  17., 130.,  83.,
        79., 367.,  33.,  25.,  38.,  26.,  88.,  29.,  21.,  28.,  84.,
       201.,  31.,  39.,  71.,  56.,  86., 197.,  36.,  94.,  67.,  70.,
       143.,  75.,  57.,  20., 142.,  61.])

In [46]:
print(df.play_star_rating.max())
print(df.play_star_rating.min())
df.play_star_rating.unique()

5.0
1.0


array([4. , 4.3, 3.6, 3.2, 3.7, 4.4, 4.1, 4.2, 3.8, 4.7, 3. , 5. , 2. ,
       nan, 4.6, 2.7, 4.5, 1. , 3.5, 3.3, 3.9, 4.8, 2.9, 3.4, 4.9, 2.5,
       2.2, 2.3, 2.8, 3.1, 2.1])

In [47]:
df.review_difficulty.value_counts()
df.review_difficulty.unique()

array(['Average', 'Easy', 'Challenging', 'Very Easy', nan,
       'Very Challenging'], dtype=object)

In [48]:
print(df.star_rating.max())
print(df.star_rating.min())
df.star_rating.unique()

5.0
1.8


array([4.5, 5. , 4.3, 4.6, 4.9, 4.2, 4.7, 4.8, 4.4, 3.4, 3. , 4. , nan,
       3.7, 3.3, 4.1, 3.9, 2.5, 3.8, 3.5, 3.6, 3.2, 2.6, 2.2, 2.7, 2.8,
       1.8, 2.9])

In [49]:
print(df.val_star_rating.max())
print(df.val_star_rating.min())
df.val_star_rating.unique()

5.0
1.0


array([4. , 4.1, 4.3, 4.4, 4.5, 3.6, 4.2, 3.5, 4.8, 5. , nan, 4.7, 3. ,
       4.6, 4.9, 3.8, 3.3, 2.5, 2.7, 2.2, 2.3, 2.8, 2. , 2.9, 3.2, 3.9,
       3.4, 2.6, 3.7, 1. , 1.8, 2.4, 1.9, 3.1])

Now that you have a bit more of a understanding of each of these features you can make an informed decision about the best strategy for dealing with the various null values. 

Some common strategies for filling null values include:
* Using the mean of the feature
* Using the median of the feature
* Inserting a random value from a normal distribution with the mean and std of the feature
* Binning

Given that most of the features with null values concern user reviews of the lego set, it is reasonable to wonder whether there is strong correlation between these features in the first place. Before proceeding, take a minute to investigate this hypothesis.

In [51]:
# Investigate whether multicollinearity exists between the review features 
# (num_reviews, play_star_rating, star_rating, val_star_rating)
df.corr()

prod_id  piece_count  list_price  num_reviews  \
prod_id           1.000000     0.221692    0.394525    -0.044658   
piece_count       0.221692     1.000000    0.865094     0.542208   
list_price        0.394525     0.865094    1.000000     0.437724   
num_reviews      -0.044658     0.542208    0.437724     1.000000   
play_star_rating -0.008234    -0.007952   -0.000685    -0.060884   
star_rating      -0.062264     0.067610   -0.006497     0.004541   
val_star_rating  -0.083703     0.067296   -0.055899     0.026664   

                  play_star_rating  star_rating  val_star_rating  
prod_id                  -0.008234    -0.062264        -0.083703  
piece_count              -0.007952     0.067610         0.067296  
list_price               -0.000685    -0.006497        -0.055899  
num_reviews              -0.060884     0.004541         0.026664  
play_star_rating          1.000000     0.619246         0.484341  
star_rating               0.619246     1.000000         0.731538  
val_star_rating           0.484341     0.731538         1.000000

Note that there is substantial correlation between the `play_star_rating`, `star_rating` and `val_star_rating`. While this could lead to multicollinearity in your eventual regression model, it is too early to clearly determine this at this point. Remember that multicollinearity is a relationship between 3 or more variables while correlation simply investigates the relationship between two variables.

Additionally, these relationships provide an alternative method for imputing missing values: since they appear to be correlated, you could use these features to help impute missing values in the others features. For example, if you are missing the `star_rating` for a particular row but have the `val_star_rating` for that same entry, it seems reasonable to assume that it is a good estimate for the missing `star_rating` value as they are highly correlated. That said, doing so does come with risks; indeed you would be further increasing the correlation between these features which could further provoke multicollinearity in the final model.

Investigate if you could use one of the other star rating features when one is missing. How many rows have one of `play_star_rating`, `star_rating` and `val_star_rating` missing, but not all three.

In [63]:
# Your code here
print('Number missing all three:',
      len(df[(df.play_star_rating.isnull())
      & (df.star_rating.isnull())
      & (df.val_star_rating.isnull())])
     )
# Number missing all three: 1421

Number missing all three: 1421


Well, it seems like when one is missing, the other two are also apt to be missing. While this has been a bit of an extended investigation, simply go ahead and fill the missing values with that feature's median. Fill in the missing values of `review_difficulty` feature  with string `'unknown'`.

In [71]:
# Your code here
df.play_star_rating = df.play_star_rating.fillna(value=df.play_star_rating.mean())
df.star_rating = df.star_rating.fillna(value=df.star_rating.mean())
df.val_star_rating = df.val_star_rating.fillna(value=df.val_star_rating.mean())
df.review_difficulty = df.review_difficulty.fillna(value='unknown')
df.prod_desc = df.prod_desc.fillna(value='unknown')
df.num_reviews = df.num_reviews.fillna(value=df.num_reviews.mean())


In [72]:
df.isna().sum()

prod_id              0
ages                 0
piece_count          0
set_name             0
prod_desc            0
prod_long_desc       0
theme_name           0
country              0
list_price           0
num_reviews          0
play_star_rating     0
review_difficulty    0
star_rating          0
val_star_rating      0
dtype: int64

## Normalizing the Data

Now, you'll need to convert all of our numeric columns to the same scale by **_normalizing_** our dataset.  Recall that you normalize a dataset by converting each numeric value to it's corresponding z-score for the column, which is obtained by subtracting the column's mean and then dividing by the column's standard deviation for every value. 


In the cell below:

* Normalize the numeric X features by subtracting the column mean and dividing by the column standard deviation. 
(Don't bother to normalize the `list_price` as this is the feature you will be predicting.)

In [96]:
# Your code here
for column in df.columns:
    if column != 'list_price':
        if df[column].dtype != 'object':
            df[column] = [(x - df[column].mean())/df[column].std() for x in df[column]]


In [97]:
df.describe()

prod_id   piece_count    list_price   num_reviews  \
count  1.087000e+04  1.087000e+04  10870.000000  1.087000e+04   
mean   7.346801e-18  1.115789e-16     67.309137  7.566696e-15   
std    1.000000e+00  1.000000e+00     94.669414  1.000000e+00   
min   -3.523768e-01 -6.050659e-01      2.272400 -4.725030e-01   
25%   -2.343560e-01 -4.895715e-01     21.899000 -4.162986e-01   
50%   -1.137005e-01 -3.379852e-01     36.587800 -3.038898e-01   
75%    5.431762e-02  6.263593e-02     73.187800  7.188413e-15   
max    1.116463e+01  8.466055e+00   1104.870000  9.812902e+00   

       play_star_rating   star_rating  val_star_rating  
count      1.087000e+04  1.087000e+04     1.087000e+04  
mean       1.390134e-13 -2.721965e-13    -7.025433e-14  
std        1.000000e+00  1.000000e+00     1.000000e+00  
min       -5.870245e+00 -5.628672e+00    -5.179606e+00  
25%       -4.468405e-01 -4.367804e-01    -3.455381e-01  
50%        7.800516e-02  1.862465e-01    -4.436632e-14  
75%        6.028508e-01  8.092735e-01     6.212755e-01  
max        1.127696e+00  1.016949e+00     1.265818e+00

## Saving Your Results

While you'll once again practice one-hot encoding as you would to preprocess data before fitting a model, saving such a reperesentation of the data will eat up additional disk space. After all, a categorical variable with 10 bins will be transformed to 10 seperate features when passed through `pd.get_dummies()`. As such, while further practice is worthwhile, save your DataFrame as is for now.

In [ ]:
# Your code here

## One-Hot Encoding Categorical Columns

As a final step, you'll need to deal with the categorical columns by **_one-hot encoding_** them into binary variables via the `pd.get_dummies()` function.  

When doing this, you may also need to subset the appropriate features to avoid encoding the wrong data. The `get_dummies()` function by default converts all columns with *object* or *category* dtype. However, you should always check the result of calling `get_dummies()` to ensure that only the categorical variables have been transformed. Consult the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html) for more details. If you are ever unsure of the data types, call the `.info()` method.

In the cell below, subset to the appropriate predictive features and then use `pd.get_dummies()` to one-hot encode the dataset properly.

In [ ]:
# Your code here

That's it! You've now successfully scrubbed your dataset -- you're now ready for data exploration and modeling!

## Summary

In this lesson, you gained practice with data cleaning by:

* Casting columns to the appropriate data types
* Identifying and dealing with null values appropriately
* Removing unnecessary columns
* Checking for and dealing with multicollinearity
* Normalizing your data