# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[3, 3, 3], [2, 2, 2], [7, 7, 7]])
display(A.dot(B+C))
display(A.dot(B) + A.dot(C))

array([[ 58,  52,  46],
       [148, 133, 118],
       [238, 214, 190]])

array([[ 58,  52,  46],
       [148, 133, 118],
       [238, 214, 190]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [7]:
# Your code here 
display(A.dot(B.dot(C))) 
display((A.dot(B)).dot(C))

array([[ 264,  264,  264],
       [ 768,  768,  768],
       [1272, 1272, 1272]])

array([[ 264,  264,  264],
       [ 768,  768,  768],
       [1272, 1272, 1272]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [5]:
# Your code here 
display(A.dot(B))
display(B.dot(A))

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [17]:
# Your code here 
display((A.T).dot(B))
display((B.T).dot(A))

array([[54, 42, 30],
       [72, 57, 42],
       [90, 72, 54]])

array([[54, 72, 90],
       [42, 57, 72],
       [30, 42, 54]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [16]:
# Your code here 
display((A.dot(B)).T)
display((B.T.dot(A.T)))

array([[ 30,  84, 138],
       [ 24,  69, 114],
       [ 18,  54,  90]])

array([[ 30,  84, 138],
       [ 24,  69, 114],
       [ 18,  54,  90]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 